# Quick question
Have you used
- dplyr
- Quarto?
- HTML?
- CSS?
- JS?
- What else?

# Pipe operator
Function composition is better written with the pipe ("then") operator `|>`

In [2]:
# With usual function composition notation
mean(head(penguins$body_mass, 3))

[1] 3600

In [10]:
# With pipe notation
penguins$body_mass |> head(3) |> mean()

[1] 3600

`A |> f |> g |> ...` plugs `A` into the first argument of `f`, then takes that output and plugs it into the first argument of `g`, so on.

To pipe into a given named argument, use `_` in the desired slot:

In [13]:
3|> head(c(10, 20, 30, 40, 50, 60), n = _)

[1] 10 20 30

# Tidy data and `tidyverse`

Data is **tidy** if
- each variable is in its own column,
- each observation is in its own row,
- each value is in its own cell.

<img src="https://statsandr.com/blog/introduction-to-data-manipulation-in-r-with-dplyr/images/tidy-data.png" width="850">

Left table below is in tidy format since each variable is a cloumn.

<img src="https://yardbook.jhelvy.com/images/data-shapes.png" width="600">

Overall `tidyverse` library is a collection of packages that follow a set of conventions like:
- tables are tidy, especially in `tibble` format.
- names use `_` and not the `.` convention from base R.
- functions use action verb naming.

## `tibble`

In a data frame, the rows can be named or have an ID.

We will use instead use a `tibble`, where rows cannot be directly named: instead the name or ID must be put as a variable.

`tibble` is the `tidyverse`'s version of a data frame without some edge cases.

In [14]:
penguins[1,] |> head()
penguins[,1] |> head()

  species island    bill_len bill_dep flipper_len body_mass sex  year
1 Adelie  Torgersen 39.1     18.7     181         3750      male 2007

[1] Adelie Adelie Adelie Adelie Adelie Adelie
Levels: Adelie Chinstrap Gentoo

In [16]:
library(tidyverse)
df <- as_tibble(penguins)
df[1,] |> head()
df[,1] |> head()

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

  species island    bill_len bill_dep flipper_len body_mass sex  year
1 Adelie  Torgersen 39.1     18.7     181         3750      male 2007

  species
1 Adelie
2 Adelie
3 Adelie
4 Adelie
5 Adelie
6 Adelie

# `dplyr` manipulates data

In [ ]:
# Load in `dplyr` library or `tidyverse` which includes `dplyr` and more.
# library(tidyverse)
library(dplyr)
library(tidyr)

In [17]:
# From https://www.kaggle.com/datasets/dhruvildave/billboard-the-hot-100-songs
read.csv("https://manctsui.github.io/datasets/charts.csv") |> as_tibble() -> df
df |> head()

  date       rank song          artist                              last.week
1 2021-11-06 1    Easy On Me    Adele                               1
2 2021-11-06 2    Stay          The Kid LAROI & Justin Bieber       2
3 2021-11-06 3    Industry Baby Lil Nas X & Jack Harlow             3
4 2021-11-06 4    Fancy Like    Walker Hayes                        4
5 2021-11-06 5    Bad Habits    Ed Sheeran                          5
6 2021-11-06 6    Way 2 Sexy    Drake Featuring Future & Young Thug 6
  peak.rank weeks.on.board
1 1          3
2 1         16
3 1         14
4 3         19
5 2         18
6 1          8

## Select columns and filter rows

Variables are named, so selecting columns is more string matching than complex logical conditions:

- Do `|> select(column_name_1,column_name_2,...)`

Observations come in many data types, so filtering rows involves complex logical conditions:

- Do `|> filter(row_condition_1, row_condition_2,...)` to AND row conditions together.

**Example 1A.** Report the song name, last week rank, and weeks on board for those songs with with missing `last.week` entries.

In [22]:
df |>
  select(song, last.week, weeks.on.board) |>
  filter(is.na(last.week))

      song                                           last.week weeks.on.board
1     Moth To A Flame                                NA         1
2     Let's Go Brandon                               NA         1
3     Not In The Mood                                NA         1
4     Switches & Dracs                               NA         1
5     Poke It Out                                    NA         1
6     Scorpio                                        NA         1
7     Big Energy                                     NA         1
8     Half Of My Hometown                            NA         1
9     Money                                          NA         1
10    To Be Loved By You                             NA         1
11    Ain't Shit                                     NA        14
12    Life Goes On                                   NA         2
13    Come Through                                   NA        16
14    Nevada                                         NA         4
15    Bubbly                                         NA         1
16    Pissed Me Off                                  NA         1
17    Lets Go Brandon                                NA         1
18    Ex For A Reason                                NA         1
19    Better Days                                    NA         1
20    Livin It Up                                    NA         1
21    Stressed                                       NA         1
22    Rich N***a Shit                                NA         1
23    Let Somebody Go                                NA         1
24    Ya Superame (En Vivo Desde Culiacan, Sinaloa)  NA         1
25    Peepin Out The Window                          NA         1
26    Who Want Smoke??                               NA         1
27    Lo Siento BB:/                                 NA         1
28    Flocky Flocky                                  NA         1
29    Easy On Me                                     NA         1
30    WFM                                            NA         1
⋮     ⋮                                              ⋮         ⋮
32283 Got A Match?                                   NA        1
32284 Stupid Cupid                                   NA        1
32285 Hey Girl - Hey Boy                             NA        1
32286 Win Your Love For Me                           NA        1
32287 Gotta Have Rain                                NA        1
32288 Midnight                                       NA        1
32289 Happy Years                                    NA        1
32290 Betty Lou Got A New Pair Of Shoes              NA        1
32291 The Bird On My Head                            NA        1
32292 Johnny B. Goode                                NA        1
32293 Beautiful Delilah                              NA        1
32294 Blip Blop                                      NA        1
32295 Try The Impossible                             NA        1
32296 Summertime Blues                               NA        1
32297 Got A Match?                                   NA        1
32298 To Be Loved                                    NA        1
32299 Jealousy                                       NA        1
32300 Just Like In The Movies                        NA        1
32301 Blue Boy                                       NA        1
32302 Stay                                           NA        1
32303 The Purple People Eater Meets The Witch Doctor NA        1
32304 Bird Dog                                       NA        1
32305 Are You Really Mine                            NA        1
32306 She Was Only Seventeen (He Was One Year More)  NA        1
32307 Little Mary                                    NA        1
32308 Over And Over                                  NA        1
32309 I Believe In You                               NA        1
32310 Little Serenade                                NA        1
32311 I'll Get By (As Long As I Have You)            NA        1
32312 Judy                                           NA        1

**Example 1B.** In above example, filter further to see if the songs with missing last week rank could have been on the board for more than 1 week.

In [25]:
df |>
  select(song, last.week, weeks.on.board) |>
  filter(is.na(last.week), weeks.on.board > 1)

     song                              last.week weeks.on.board
1    Ain't Shit                        NA        14
2    Life Goes On                      NA         2
3    Come Through                      NA        16
4    Nevada                            NA         4
5    Maybach                           NA         3
6    Woo Baby                          NA         2
7    Ain't Shit                        NA        13
8    For Tonight                       NA         2
9    Praise God                        NA         3
10   Blue Note$ II                     NA         2
11   One Mississippi                   NA         2
12   Ghost                             NA         2
13   Sand In My Boots                  NA        12
14   Sun Goes Down                     NA         2
15   In Da Getto                       NA         2
16   Come Through                      NA        14
17   Cold Heart (PNAU Remix)           NA         2
18   Knowing You                       NA         5
19   Repeat It                         NA         3
20   Holy Smokes                       NA         3
21   Miss The Rage                     NA        11
22   Brutal                            NA        11
23   Get Into It (Yuh)                 NA         2
24   5500 Degrees                      NA         2
25   Cold As You                       NA         2
26   Woman                             NA         2
27   WUSYANAME                         NA         6
28   Next Girl                         NA         3
29   Twerkulator                       NA         9
30   Lost Cause                        NA         4
⋮    ⋮                                 ⋮         ⋮
2599 Little Red Riding Hood            NA        4
2600 The World Outside                 NA        3
2601 (I Wanna) Dance With The Teacher  NA        2
2602 Joe Joe Gunne                     NA        4
2603 Dreamy Eyes                       NA        3
2604 Seven Minutes In Heaven           NA        2
2605 Crazy Country Hop                 NA        4
2606 A House, A Car And A Wedding Ring NA        3
2607 Cinderella                        NA        2
2608 It Don't Hurt No More             NA        2
2609 It's Raining Outside              NA        2
2610 I'll Wait For You                 NA        2
2611 Big Daddy                         NA        2
2612 A Lover's Question                NA        2
2613 My Lucky Love                     NA        4
2614 The Ballad Of Thunder Road        NA        3
2615 When Will I Know                  NA        4
2616 You Cheated                       NA        5
2617 Fire Of Love                      NA        4
2618 Gas Money                         NA        2
2619 Blue Boy                          NA        5
2620 Alone With You                    NA        4
2621 You're A Sweetheart               NA        4
2622 Where The Blue Of The Night       NA        2
2623 Leroy                             NA        3
2624 Drip Drop                         NA        2
2625 Hey Girl - Hey Boy                NA        2
2626 Just Like In The Movies           NA        2
2627 Delicious!                        NA        2
2628 Blip Blop                         NA        2

Common `select` patterns, including use with helper functions:
- `|> select(col_A:col_Z)` select columns between `col_A` and `col_Z` inclusive.
- `|> select(contains("string"))` selects column names containing "string"
- `|> select(matches(".t"))` selects column names matching regular expression ".t"
- `|> select(starts_with("string"))` selects column names starting with "string"
- `|> select(ends_with("string"))` selects column names ending with "string"
- `|> select(where(is.numeric))` selects numeric columns
- `|> select(col_A, col_B, everything())` reorders columns so that `col_A` and `col_B` come first: `everything` fills in with the rest of the columns.

## More column operations: `mutate`
`|> mutate(column = formula)` writes over old column name or writes a new column according to formula.

**Example.** Add a column which states number of days the song is on the charts.

In [26]:
df |>
  mutate(days.on.board = 7 * weeks.on.board)

       date       rank song
1      2021-11-06  1   Easy On Me
2      2021-11-06  2   Stay
3      2021-11-06  3   Industry Baby
4      2021-11-06  4   Fancy Like
5      2021-11-06  5   Bad Habits
6      2021-11-06  6   Way 2 Sexy
7      2021-11-06  7   Shivers
8      2021-11-06  8   Good 4 U
9      2021-11-06  9   Need To Know
10     2021-11-06 10   Levitating
11     2021-11-06 11   Essence
12     2021-11-06 12   Kiss Me More
13     2021-11-06 13   Heat Waves
14     2021-11-06 14   Beggin'
15     2021-11-06 15   Cold Heart (PNAU Remix)
16     2021-11-06 16   You Right
17     2021-11-06 17   Save Your Tears
18     2021-11-06 18   If I Didn't Love You
19     2021-11-06 19   Traitor
20     2021-11-06 20   My Universe
21     2021-11-06 21   Who Want Smoke??
22     2021-11-06 22   Knife Talk
23     2021-11-06 23   Meet Me At Our Spot
24     2021-11-06 24   Montero (Call Me By Your Name)
25     2021-11-06 25   Chasing After You
26     2021-11-06 26   Girls Want Girls
27     2021-11-06 27   Moth To A Flame
28     2021-11-06 28   Let's Go Brandon
29     2021-11-06 29   Thats What I Want
30     2021-11-06 30   Pepas
⋮      ⋮          ⋮    ⋮
330058 1958-08-04  71  Got A Match?
330059 1958-08-04  72  Stupid Cupid
330060 1958-08-04  73  Hey Girl - Hey Boy
330061 1958-08-04  74  Win Your Love For Me
330062 1958-08-04  74  Gotta Have Rain
330063 1958-08-04  76  Midnight
330064 1958-08-04  77  Happy Years
330065 1958-08-04  78  Betty Lou Got A New Pair Of Shoes
330066 1958-08-04  79  The Bird On My Head
330067 1958-08-04  80  Johnny B. Goode
330068 1958-08-04  81  Beautiful Delilah
330069 1958-08-04  82  Blip Blop
330070 1958-08-04  83  Try The Impossible
330071 1958-08-04  84  Summertime Blues
330072 1958-08-04  85  Got A Match?
330073 1958-08-04  86  To Be Loved
330074 1958-08-04  87  Jealousy
330075 1958-08-04  88  Just Like In The Movies
330076 1958-08-04  89  Blue Boy
330077 1958-08-04  90  Stay
330078 1958-08-04  91  The Purple People Eater Meets The Witch Doctor
330079 1958-08-04  92  Bird Dog
330080 1958-08-04  93  Are You Really Mine
330081 1958-08-04  94  She Was Only Seventeen (He Was One Year More)
330082 1958-08-04  95  Little Mary
330083 1958-08-04  96  Over And Over
330084 1958-08-04  97  I Believe In You
330085 1958-08-04  98  Little Serenade
330086 1958-08-04  99  I'll Get By (As Long As I Have You)
330087 1958-08-04 100  Judy
       artist                                             last.week peak.rank
1      Adele                                               1         1
2      The Kid LAROI & Justin Bieber                       2         1
3      Lil Nas X & Jack Harlow                             3         1
4      Walker Hayes                                        4         3
5      Ed Sheeran                                          5         2
6      Drake Featuring Future & Young Thug                 6         1
7      Ed Sheeran                                          9         7
8      Olivia Rodrigo                                      7         1
9      Doja Cat                                           11         9
10     Dua Lipa                                            8         2
11     Wizkid Featuring Justin Bieber & Tems              12         9
12     Doja Cat Featuring SZA                             10         3
13     Glass Animals                                      14        12
14     Maneskin                                           15        14
15     Elton John & Dua Lipa                              21        15
16     Doja Cat & The Weeknd                              16        11
17     The Weeknd & Ariana Grande                         17         1
18     Jason Aldean & Carrie Underwood                    23        15
19     Olivia Rodrigo                                     22         9
20     Coldplay x BTS                                     13         1
21     Nardo Wick Featuring G Herbo, Lil Durk & 21 Savage 19        17
22     Drake Featuring 21 Savage & Project Pat            18         4
23     THE ANXIETY: WILLOW & Tyler Cole                   32        23
24     Lil Nas X                                          24         1
25     Ryan Hurd With Maren Morris                        25        23
26     Drake Featuring Lil Baby                           26         2
27     Swedish House Mafia & The Weeknd                   NA        27
28     Bryson Gray Featuring Tyson James & Chandler Crump NA        28
29     Lil Nas X                                          28        10
30     Farruko                                            29        25
⋮      ⋮                                                  ⋮         ⋮
330058 Frank Gallup                                       NA         71
330059 Connie Francis                                     NA         72
330060 Oscar McLollie and Jeanette Baker                  NA         73
330061 Sam Cooke                                          NA         74
330062 Eydie Gorme                                        NA         74
330063 Paul Anka                                          NA         76
330064 The Diamonds                                       NA         77
330065 Bobby Freeman                                      NA         78
330066 David Seville                                      NA         79
330067 Chuck Berry                                        NA         80
330068 Chuck Berry                                        NA         81
330069 Bill Doggett                                       NA         82
330070 Lee Andrews And The Hearts                         NA         83
330071 Eddie Cochran                                      NA         84
330072 The Daddy-O's                                      NA         85
330073 Jackie Wilson                                      NA         86
330074 Kitty Wells                                        NA         87
330075 The Upbeats                                        NA         88
330076 Jim Reeves                                         NA         89
330077 The Ames Brothers                                  NA         90
330078 Joe South                                          NA         91
330079 The Everly Brothers                                NA         92
330080 Jimmie Rodgers                                     NA         93
330081 Marty Robbins                                      NA         94
330082 Fats Domino                                        NA         95
330083 Thurston Harris                                    NA         96
330084 Robert & Johnny                                    NA         97
330085 The Ames Brothers                                  NA         98
330086 Billy Williams                                     NA         99
330087 Frankie Vaughan                                    NA        100
       weeks.on.board days.on.board
1       3              21
2      16             112
3      14              98
4      19             133
5      18             126
6       8              56
7       7              49
8      24             168
9      20             140
10     56             392
11     17             119
12     29             203
13     41             287
14     18             126
15      8              56
16     18             126
17     46             322
18     14              98
19     23             161
20      5              35
21      3              21
22      8              56
23      7              49
24     31             217
25     26             182
26      8              56
27      1               7
28      1               7
29      6              42
30     14              98
⋮      ⋮              ⋮
330058 1              7
330059 1              7
330060 1              7
330061 1              7
330062 1              7
330063 1              7
330064 1              7
330065 1              7
330066 1              7
330067 1              7
330068 1              7
330069 1              7
330070 1              7
330071 1              7
330072 1              7
330073 1              7
330074 1              7
330075 1              7
330076 1              7
330077 1              7
330078 1              7
330079 1              7
330080 1              7
330081 1              7
330082 1              7
330083 1              7
330084 1              7
330085 1              7
330086 1              7
330087 1              7

# More row operations
Common row manipulation patterns:
- `|> drop_na(col_A, col_B)` removes all NA values from `colA` and `col_B` from `tidyr`.
- `|> distinct(col_A, col_B)` removes all duplicate rows occurring as `(col_A, col_B)`.
- `|> arrange(col_A, desc(col_B))` sorts by `col_A` ascending and then `col_B` descending.
- `|> slice(your_vector)` returns the data frame or tibble of rows indexed by `your_vector`.

**Example.** Return songs by Olivia Rodrigo, with no repeated songs, with newest songs first.

In [38]:
df |>
  filter(artist == 'Olivia Rodrigo') |>
  arrange(desc(date), weeks.on.board) |>
  distinct(song, .keep_all = TRUE)

   date       rank song                         artist         last.week
1  2021-11-06  19  Traitor                      Olivia Rodrigo 22
2  2021-11-06   8  Good 4 U                     Olivia Rodrigo  7
3  2021-10-30  50  Deja Vu                      Olivia Rodrigo 42
4  2021-09-11  97  Brutal                       Olivia Rodrigo 89
5  2021-08-28  93  Favorite Crime               Olivia Rodrigo 89
6  2021-08-21  97  Happier                      Olivia Rodrigo 93
7  2021-07-31  99  Jealousy, Jealousy           Olivia Rodrigo 87
8  2021-07-31  43  Drivers License              Olivia Rodrigo 42
9  2021-07-17  98  Enough For You               Olivia Rodrigo NA
10 2021-06-26  95  1 Step Forward, 3 Steps Back Olivia Rodrigo 65
11 2021-06-19  84  Hope Ur OK                   Olivia Rodrigo 52
12 2020-01-25 100  All I Want                   Olivia Rodrigo 90
   peak.rank weeks.on.board
1   9        23
2   1        24
3   3        29
4  12        12
5  16        13
6  15        12
7  24         9
8   1        28
9  14         6
10 19         4
11 29         3
12 90         2

**Example.** Remove all NA values from `last.week` and `weeks.on.board`, arrange by least to most weeks on board, and remove repeated songs.

In [42]:
df |>
  drop_na(last.week, weeks.on.board) |>
  arrange(weeks.on.board) |>
  distinct(song, .keep_all = T)

      date       rank
1     2021-11-06  35
2     2021-11-06  38
3     2021-11-06  45
4     2021-11-06  62
5     2021-11-06  92
6     2021-10-30   1
7     2021-10-30  19
8     2021-10-30  67
9     2021-10-30  73
10    2021-10-30  76
11    2021-10-30  83
12    2021-10-30  84
13    2021-10-30  96
14    2021-10-30  98
15    2021-10-30  99
16    2021-10-30 100
17    2021-10-23  61
18    2021-10-23  69
19    2021-10-23  82
20    2021-10-16  12
21    2021-10-16  59
22    2021-10-16  61
23    2021-10-16  80
24    2021-10-16  81
25    2021-10-16  86
26    2021-10-16 100
27    2021-10-09  24
28    2021-10-09  37
29    2021-10-09  50
30    2021-10-09  95
⋮     ⋮          ⋮
22537 2016-12-24 86
22538 2015-10-31 91
22539 2015-02-21 99
22540 2015-01-17 71
22541 2014-08-30 97
22542 2014-07-05 85
22543 2014-01-04 86
22544 2013-07-20 92
22545 2013-04-13 82
22546 2013-04-06 26
22547 2013-02-02 79
22548 2012-06-09 92
22549 2012-01-28 21
22550 2011-12-17 95
22551 2011-03-12 99
22552 2010-11-13 95
22553 2010-02-20 72
22554 2010-01-09 66
22555 2009-10-10 89
22556 1971-03-06 95
22557 1964-01-04 84
22558 1963-02-23 89
22559 1962-03-03 96
22560 1960-07-25 93
22561 1959-01-12 71
22562 2017-04-22 90
22563 2016-12-10 95
22564 2014-01-18 89
22565 2009-03-07 83
22566 1976-07-04 98
      song
1     Better Days
2     Lets Go Brandon
3     Bubbly
4     Pissed Me Off
5     Ya Superame (En Vivo Desde Culiacan, Sinaloa)
6     Easy On Me
7     Who Want Smoke??
8     WFM
9     Lo Siento BB:/
10    'Til You Can't
11    Tequila Little Time
12    Freedom Was A Highway
13    Who's In Your Head
14    Flocky Flocky
15    Like A Lady
16    Just About Over You
17    Esta Danada
18    Jugaste y Sufri
19    Whiskey And Rain
20    My Universe
21    Too Easy
22    Your Heart
23    Chosen
24    Bad Morning
25    Nevada
26    No Where
27    Thats What I Want
28    On My Side
29    Love Nwantiti (Ah Ah Ah)
30    Same Boat
⋮     ⋮
22537 False Alarm
22538 Stressed Out
22539 I Mean It
22540 Style
22541 Dust
22542 We Are One (Ole Ola) [The 2014 FIFA World Cup Official Song]
22543 See You Tonight
22544 Beneath Your Beautiful
22545 Karate Chop (Remix)
22546 22
22547 Kiss You
22548 Same Damn Time
22549 Stronger (What Doesn't Kill You)
22550 The Trouble With Girls
22551 U Smile
22552 Waiting For The End
22553 Hey Daddy (Daddy's Home)
22554 Imma Be
22555 Fifteen
22556 Timothy
22557 Baby's Gone
22558 Bossa Nova U.S.A.
22559 Aw Shucks, Hush Your Mouth
22560 Big Boy Pete
22561 (I Wanna) Dance With The Teacher
22562 Scared To Be Lonely
22563 Sex With Me
22564 The Heart Of Dixie
22565 Lost!
22566 Rhiannon (Will You Ever Win)
      artist                                             last.week peak.rank
1     NEIKED X Mae Muller X Polo G                       57        35
2     Loza Alexander                                     45        38
3     Young Thug With Drake & Travis Scott               20        20
4     Lil Durk                                           39        39
5     Grupo Firme                                        92        92
6     Adele                                              68         1
7     Nardo Wick Featuring G Herbo, Lil Durk & 21 Savage 17        17
8     Realestk                                           75        67
9     Tainy, Bad Bunny & Julieta Venegas                 51        51
10    Cody Johnson                                       94        76
11    Jon Pardi                                          86        83
12    Jimmie Allen & Brad Paisley                        88        84
13    Jonas Brothers                                     95        95
14    Don Toliver Featuring Travis Scott                 53        53
15    Lady A                                             90        90
16    Priscilla Block                                    97        97
17    Ivan Cornejo                                       96        61
18    Eslabon Armado Featuring DannyLux                  75        69
19    Michael Ray                                        97        82
20    Coldplay x BTS                                      1         1
21    Gunna & Future                                     38        38
22    Joyner Lucas & J. Cole                             32        32
23    Blxst & Tyga Featuring Ty Dolla $ign               98        80
24    YoungBoy Never Broke Again                         28        28
25    YoungBoy Never Broke Again                         58        58
26    YoungBoy Never Broke Again                         40        40
27    Lil Nas X                                          10        10
28    YoungBoy Never Broke Again                         71        37
29    CKay                                               80        50
30    Zac Brown Band                                     98        95
⋮     ⋮                                                  ⋮         ⋮
22537 The Weeknd                                          55       55
22538 twenty one pilots                                   95       87
22539 G-Eazy Featuring Remo                               98       98
22540 Taylor Swift                                        84       60
22541 Eli Young Band                                     100       97
22542 Pitbull Featuring Jennifer Lopez & Claudia Leitte   59       59
22543 Scotty McCreery                                     86       86
22544 Labrinth Featuring Emeli Sande                      95       88
22545 Future Featuring Lil Wayne                          93       82
22546 Taylor Swift                                        64       26
22547 One Direction                                       65       65
22548 Future                                              97       92
22549 Kelly Clarkson                                      58       21
22550 Scotty McCreery                                     93       84
22551 Justin Bieber                                       94       27
22552 Linkin Park                                        100       95
22553 Usher Featuring Plies                               80       72
22554 The Black Eyed Peas                                 93       50
22555 Taylor Swift                                        94       65
22556 The Buoys                                           99       93
22557 Gene Thomas                                         87       84
22558 The Dave Brubeck Quartet                            96       83
22559 Jimmy Reed                                          97       93
22560 The Olympics                                        97       92
22561 The Olympics                                        77       71
22562 Martin Garrix & Dua Lipa                            92       88
22563 Rihanna                                             92       92
22564 Danielle Bradbery                                   93       58
22565 Coldplay With Jay-Z                                 40       40
22566 Fleetwood Mac                                       42       11
      weeks.on.board
1     2
2     2
3     2
4     2
5     2
6     2
7     2
8     2
9     2
10    2
11    2
12    2
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    2
25    2
26    2
27    2
28    2
29    2
30    2
⋮     ⋮
22537  4
22538  4
22539  4
22540  4
22541  4
22542  4
22543  4
22544  4
22545  4
22546  4
22547  4
22548  4
22549  4
22550  4
22551  4
22552  4
22553  4
22554  4
22555  4
22556  4
22557  4
22558  4
22559  4
22560  4
22561  4
22562  5
22563  5
22564  5
22565  5
22566 18

# Grouping and summarizing

`|> group_by(col_A, col_B)` groups data so that `col_A, col_B` are together.

`|> summarize(fn_1(col_A), fn_2(col_B))` summarizes `col_A` using `fn_1` and `col_B` using `fn_2`.

**Example.** Group by artists, then by songs.

In [43]:
df |>
  group_by(artist, song)

       date       rank song
1      2021-11-06  1   Easy On Me
2      2021-11-06  2   Stay
3      2021-11-06  3   Industry Baby
4      2021-11-06  4   Fancy Like
5      2021-11-06  5   Bad Habits
6      2021-11-06  6   Way 2 Sexy
7      2021-11-06  7   Shivers
8      2021-11-06  8   Good 4 U
9      2021-11-06  9   Need To Know
10     2021-11-06 10   Levitating
11     2021-11-06 11   Essence
12     2021-11-06 12   Kiss Me More
13     2021-11-06 13   Heat Waves
14     2021-11-06 14   Beggin'
15     2021-11-06 15   Cold Heart (PNAU Remix)
16     2021-11-06 16   You Right
17     2021-11-06 17   Save Your Tears
18     2021-11-06 18   If I Didn't Love You
19     2021-11-06 19   Traitor
20     2021-11-06 20   My Universe
21     2021-11-06 21   Who Want Smoke??
22     2021-11-06 22   Knife Talk
23     2021-11-06 23   Meet Me At Our Spot
24     2021-11-06 24   Montero (Call Me By Your Name)
25     2021-11-06 25   Chasing After You
26     2021-11-06 26   Girls Want Girls
27     2021-11-06 27   Moth To A Flame
28     2021-11-06 28   Let's Go Brandon
29     2021-11-06 29   Thats What I Want
30     2021-11-06 30   Pepas
⋮      ⋮          ⋮    ⋮
330058 1958-08-04  71  Got A Match?
330059 1958-08-04  72  Stupid Cupid
330060 1958-08-04  73  Hey Girl - Hey Boy
330061 1958-08-04  74  Win Your Love For Me
330062 1958-08-04  74  Gotta Have Rain
330063 1958-08-04  76  Midnight
330064 1958-08-04  77  Happy Years
330065 1958-08-04  78  Betty Lou Got A New Pair Of Shoes
330066 1958-08-04  79  The Bird On My Head
330067 1958-08-04  80  Johnny B. Goode
330068 1958-08-04  81  Beautiful Delilah
330069 1958-08-04  82  Blip Blop
330070 1958-08-04  83  Try The Impossible
330071 1958-08-04  84  Summertime Blues
330072 1958-08-04  85  Got A Match?
330073 1958-08-04  86  To Be Loved
330074 1958-08-04  87  Jealousy
330075 1958-08-04  88  Just Like In The Movies
330076 1958-08-04  89  Blue Boy
330077 1958-08-04  90  Stay
330078 1958-08-04  91  The Purple People Eater Meets The Witch Doctor
330079 1958-08-04  92  Bird Dog
330080 1958-08-04  93  Are You Really Mine
330081 1958-08-04  94  She Was Only Seventeen (He Was One Year More)
330082 1958-08-04  95  Little Mary
330083 1958-08-04  96  Over And Over
330084 1958-08-04  97  I Believe In You
330085 1958-08-04  98  Little Serenade
330086 1958-08-04  99  I'll Get By (As Long As I Have You)
330087 1958-08-04 100  Judy
       artist                                             last.week peak.rank
1      Adele                                               1         1
2      The Kid LAROI & Justin Bieber                       2         1
3      Lil Nas X & Jack Harlow                             3         1
4      Walker Hayes                                        4         3
5      Ed Sheeran                                          5         2
6      Drake Featuring Future & Young Thug                 6         1
7      Ed Sheeran                                          9         7
8      Olivia Rodrigo                                      7         1
9      Doja Cat                                           11         9
10     Dua Lipa                                            8         2
11     Wizkid Featuring Justin Bieber & Tems              12         9
12     Doja Cat Featuring SZA                             10         3
13     Glass Animals                                      14        12
14     Maneskin                                           15        14
15     Elton John & Dua Lipa                              21        15
16     Doja Cat & The Weeknd                              16        11
17     The Weeknd & Ariana Grande                         17         1
18     Jason Aldean & Carrie Underwood                    23        15
19     Olivia Rodrigo                                     22         9
20     Coldplay x BTS                                     13         1
21     Nardo Wick Featuring G Herbo, Lil Durk & 21 Savage 19        17
22     Drake Featuring 21 Savage & Project Pat            18         4
23     THE ANXIETY: WILLOW & Tyler Cole                   32        23
24     Lil Nas X                                          24         1
25     Ryan Hurd With Maren Morris                        25        23
26     Drake Featuring Lil Baby                           26         2
27     Swedish House Mafia & The Weeknd                   NA        27
28     Bryson Gray Featuring Tyson James & Chandler Crump NA        28
29     Lil Nas X                                          28        10
30     Farruko                                            29        25
⋮      ⋮                                                  ⋮         ⋮
330058 Frank Gallup                                       NA         71
330059 Connie Francis                                     NA         72
330060 Oscar McLollie and Jeanette Baker                  NA         73
330061 Sam Cooke                                          NA         74
330062 Eydie Gorme                                        NA         74
330063 Paul Anka                                          NA         76
330064 The Diamonds                                       NA         77
330065 Bobby Freeman                                      NA         78
330066 David Seville                                      NA         79
330067 Chuck Berry                                        NA         80
330068 Chuck Berry                                        NA         81
330069 Bill Doggett                                       NA         82
330070 Lee Andrews And The Hearts                         NA         83
330071 Eddie Cochran                                      NA         84
330072 The Daddy-O's                                      NA         85
330073 Jackie Wilson                                      NA         86
330074 Kitty Wells                                        NA         87
330075 The Upbeats                                        NA         88
330076 Jim Reeves                                         NA         89
330077 The Ames Brothers                                  NA         90
330078 Joe South                                          NA         91
330079 The Everly Brothers                                NA         92
330080 Jimmie Rodgers                                     NA         93
330081 Marty Robbins                                      NA         94
330082 Fats Domino                                        NA         95
330083 Thurston Harris                                    NA         96
330084 Robert & Johnny                                    NA         97
330085 The Ames Brothers                                  NA         98
330086 Billy Williams                                     NA         99
330087 Frankie Vaughan                                    NA        100
       weeks.on.board
1       3
2      16
3      14
4      19
5      18
6       8
7       7
8      24
9      20
10     56
11     17
12     29
13     41
14     18
15      8
16     18
17     46
18     14
19     23
20      5
21      3
22      8
23      7
24     31
25     26
26      8
27      1
28      1
29      6
30     14
⋮      ⋮
330058 1
330059 1
330060 1
330061 1
330062 1
330063 1
330064 1
330065 1
330066 1
330067 1
330068 1
330069 1
330070 1
330071 1
330072 1
330073 1
330074 1
330075 1
330076 1
330077 1
330078 1
330079 1
330080 1
330081 1
330082 1
330083 1
330084 1
330085 1
330086 1
330087 1

**Example.** For each artist, what is the most weeks that some song they had spent on the Billboard?

In [47]:
df |>
  group_by(artist) |>
  summarize(max(weeks.on.board)) |>
  head(10)

      artist
1     "Groove" Holmes
2     "Little" Jimmy Dickens
3     "Pookie" Hudson
4     "Weird Al" Yankovic
5     'N Sync
6     'N Sync & Gloria Estefan
7     'N Sync Featuring Nelly
8     'Til Tuesday
9     (+44)
10    (The Preacher) Bobby Womack
11    1 Of The Girls
12    10 Years
13    10,000 Maniacs
14    100 Proof Aged in Soul
15    100 Strings and Jono (Choir of 40 Voices)
16    10cc
17    112
18    112 Featuring Foxy Brown
19    112 Featuring Lil'z
20    112 Featuring Ludacris
21    112 Featuring Mase
22    112 Featuring Super Cat
23    112 Featuring The Notorious B.I.G.
24    12 Gauge
25    1910 Fruitgum Co.
26    1927
27    2 Chainz
28    2 Chainz & Wiz Khalifa
29    2 Chainz Featuring Ariana Grande
30    2 Chainz Featuring Drake
⋮     ⋮
10176 a-ha
10177 alt-J
10178 benny blanco & Juice WRLD Featuring Brendon Urie
10179 benny blanco, Halsey & Khalid
10180 benny blanco, Tainy, Selena Gomez & J Balvin
10181 blackbear
10182 dc Talk
10183 deadmau5 Featuring Greta Svabo Bech
10184 dog's eye view
10185 for KING & COUNTRY
10186 fun.
10187 fun. Featuring Janelle Monae
10188 gnash Featuring Johnny Yukon
10189 gnash Featuring Olivia O'Brien
10190 iLoveMemphis
10191 iio
10192 j-hope Featuring Becky G.
10193 k.d. lang
10194 lovelytheband
10195 matchbox 20
10196 matchbox twenty
10197 t.A.T.u.
10198 twenty one pilots
10199 will.i.am
10200 will.i.am & Britney Spears
10201 will.i.am & Nicki Minaj
10202 will.i.am Featuring Justin Bieber
10203 will.i.am Featuring Mick Jagger & Jennifer Lopez
10204 will.i.am Featuring Miley Cyrus
10205 will.i.am Featuring Miley Cyrus, French Montana, Wiz Khalifa & DJ Mustard
      max(weeks.on.board)
1     11
2     10
3      1
4     20
5     26
6     20
7     20
8     21
9      1
10     9
11     4
12     2
13    29
14    14
15     1
16    19
17    29
18    20
19    25
20     9
21    16
22     6
23    28
24    21
25    14
26     1
27    20
28     7
29     2
30    26
⋮     ⋮
10176 27
10177  1
10178  6
10179 52
10180  5
10181 42
10182 19
10183  1
10184 14
10185  1
10186 56
10187 42
10188  1
10189 39
10190 20
10191 15
10192  1
10193 19
10194 22
10195 28
10196 54
10197 20
10198 52
10199  9
10200 24
10201 15
10202 16
10203  8
10204  1
10205  2

In [49]:
# Sanity check: see if Ed Sheeran actually have that max number of weeks
 df |>
   filter(artist == "Ed Sheeran") |>
   group_by(artist) |>
   summarize(max(weeks.on.board), .groups = "drop") |>
   head(10)

 df |>
   filter(artist == "Ed Sheeran") |>
   arrange(desc(weeks.on.board)) |>
   head(3)

  artist     max(weeks.on.board)
1 Ed Sheeran 59

  date       rank song              artist     last.week peak.rank
1 2018-03-03 24   Shape Of You      Ed Sheeran 24        1
2 2018-02-24 24   Shape Of You      Ed Sheeran 23        1
3 2015-11-28 45   Thinking Out Loud Ed Sheeran 41        2
  weeks.on.board
1 59
2 58
3 58

## Big pictures


| Column | Row | Group (Do last) |
|--------|-----|-----------------|
| select | filter    | group_by  |
| mutate | drop_na   | summarize |
|        | distinct  | count     |
|        | slice     |           |
|        | arrange   |           |

# What else (optional topics, not required for class)

Learn to do joins in `dplyr`.

Learn more R packages:
- `tidyverse` loads `dplyr`, `stringr` (string manipulation), `readr`, `tibble`, `ggplot2` (graphs), etc.
- `lubridate` (date manipulation)
- `data.table` (`dplyr` alternative)
- `janitor` (use before `dplyr` to clean data)